### ISSUE TITLE
Error while building

### ISSUE THREAD

**Issue by idkjs** [letouzey/sketch-downloader#1]
Tried to build this since Sketch links dont seem to work at the moment.

Here is the error i got

```bash
 [I] ➜ opam install biniou
The following actions will be performed:
  ∗ install biniou 1.2.1

<><> Gathering sources <><><><><>  🐫 
[biniou.1.2.1] found in cache

<><> Processing actions ><><><><>  🐫 

#=== ERROR while installing biniou.1.2.1 
# path        /Volumes/external/.opam/4.10.0/.opam-switch/build/biniou.1.2.1
# command     /Volumes/external/.opam/4.10.0/.opam-switch/build/biniou.1.2.1/./install -m 0755 /Volumes/external/.opam/4.10.0/.opam-switch/build/biniou.1.2.1/_build/install/default/bin/bdump /Volumes/external/.opam/4.10.0/bin/bdump
# exit-code   2
# env-file    /Volumes/external/.opam/log/log-99772-e7966f.env
# output-file /Volumes/external/.opam/log/log-99772-e7966f.out
### output ###
# /Volumes/external/.opam/4.10.0/.opam-switch/build/biniou.1.2.1/./install: line 1: Installation: command not found
# /Volumes/external/.opam/4.10.0/.opam-switch/build/biniou.1.2.1/./install: line 4: Requirements:: command not found
# /Volumes/external/.opam/4.10.0/.opam-switch/build/biniou.1.2.1/./install: line 6: syntax error near unexpected token `('
# /Volumes/external/.opam/4.10.0/.opam-switch/build/biniou.1.2.1/./install: line 6: `- Objective Caml (>= 3.11 is fine, earlier versions are probably fine too)'



<><> Error report ><><><><><><><>  🐫 
┌─ The following actions failed
│ ∗ install biniou 1.2.1
└─ 
╶─ No changes have been performed
```

Any ideas?

Thanks for sharing

**Comment by letouzey** [comment]
Hi
This looks like you're on a case-insensitive system (mac or windows) and opam has confused the `install` binary program with the `INSTALL` text file provided in the biniou sources. And trying to execute this `INSTALL` text file as a shell script doesn't work, obviously. I suggest you report this issue directly to the opam developers (provided that your system is indeed mentioned as supported by opam) : https://github.com/ocaml/opam/issues .
Meanwhile, I advise you to try if possible in a linux virtual image (for instance a ubuntu docker), that should solve this case-insensitivity issue. And at least for fetching from the `sketch` database, you could try the `getsketch.sh` shell script, it doesn't require any compilation nor ocaml, just the curl tool. But it outputs a JSON dump of the sketch page, and that's why biniou/yojson is needed in my little tools (either the ocaml `getsketch` or `transketch`). 
Best regards

**Comment by idkjs** [comment]
Wow. Awesome answer. Since this has not happened before, I wonder if this has to do with installing my opam on my external drive because it keeps filling up my primary hard drives 20GB of available space. I will mess with my new setup before I hit opam about. Thanks so much for the very informative answer. Also reminds me that I now have space for Docker on ssd!
